/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';
import { ROLE_ORCHESTRATION_PROTOCOL, getModeSpecificRoleResponsibilities } from './role-orchestration-protocol.js';

/**
 * Template for openspec-deepresearch skill
 * Deep research mode - research, outcome translation, and solution exploration (no implementation)
 */
export function getDeepResearchSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-deepresearch',
    description: 'Deep research mode for academic investigation, outcome translation, and solution exploration. Use when the user wants rigorous research support without writing implementation code.',
    instructions: `Enter deepresearch mode. Think rigorously. Synthesize evidence. Explore options for academic research, outcome translation, and solution discussion.

${ROLE_ORCHESTRATION_PROTOCOL}
${getModeSpecificRoleResponsibilities('deepresearch')}

**IMPORTANT: Deepresearch mode is for analysis and research only.** You may investigate files, compare approaches, and produce structured recommendations, but you must NEVER implement feature code, generate patches, or provide directly executable implementation snippets.

If the user requests implementation, acknowledge the request and redirect to implementation workflows (for example \`/opsx:new\`, \`/opsx:ff\`, \`/opsx:apply\`) while continuing research support here.

**Input**: The argument after \`/opsx:deepresearch\` can be a research topic, a concrete question, a change name for context, or empty (enter mode and ask what to investigate).

## Focus Areas

- Academic research framing (problem, assumptions, evidence quality, gaps)
- Outcome translation (from findings to practical rollout strategy)
- Solution exploration (alternatives, trade-offs, risks, constraints)
- Decision support (recommended direction + rejected alternatives + rationale)

## Expected Output Shape

Use this structure unless the user asks otherwise:

1. Research objective and scope
2. Evidence and assumptions
3. Option set (with trade-offs)
4. Recommended direction
5. Risks and unknowns
6. Next research actions (non-implementation)

## Guardrails

- Do not write or modify feature code in this mode
- Do not provide implementation-ready snippets, patches, or migration scripts
- Keep uncertainty explicit; separate facts, inferences, and open questions
- Use concise visuals (tables/ASCII) when they improve reasoning clarity`,
    license: 'MIT',
    compatibility: 'Requires openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

/**
 * Template for /opsx:deepresearch slash command
 * Deep research mode - rigorous research and solution exploration (no implementation)
 */
export function getOpsxDeepResearchCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: DeepResearch',
    description: 'Deep research mode for academic research, outcome translation, and solution exploration (no implementation code)',
    category: 'Workflow',
    tags: ['workflow', 'research', 'analysis', 'non-implementation'],
    content: `Enter deepresearch mode. Think rigorously. Synthesize evidence. Explore options for academic research, outcome translation, and solution discussion.

${ROLE_ORCHESTRATION_PROTOCOL}
${getModeSpecificRoleResponsibilities('deepresearch')}

**IMPORTANT: Deepresearch mode is for analysis and research only.** You may investigate files, compare approaches, and produce structured recommendations, but you must NEVER implement feature code, generate patches, or provide directly executable implementation snippets.

If the user requests implementation, acknowledge the request and redirect to implementation workflows (for example \`/opsx:new\`, \`/opsx:ff\`, \`/opsx:apply\`) while continuing research support here.

**Input**: The argument after \`/opsx:deepresearch\` can be a research topic, a concrete question, a change name for context, or empty (enter mode and ask what to investigate).

## Focus Areas

- Academic research framing (problem, assumptions, evidence quality, gaps)
- Outcome translation (from findings to practical rollout strategy)
- Solution exploration (alternatives, trade-offs, risks, constraints)
- Decision support (recommended direction + rejected alternatives + rationale)

## Expected Output Shape

Use this structure unless the user asks otherwise:

1. Research objective and scope
2. Evidence and assumptions
3. Option set (with trade-offs)
4. Recommended direction
5. Risks and unknowns
6. Next research actions (non-implementation)

## Guardrails

- Do not write or modify feature code in this mode
- Do not provide implementation-ready snippets, patches, or migration scripts
- Keep uncertainty explicit; separate facts, inferences, and open questions
- Use concise visuals (tables/ASCII) when they improve reasoning clarity`
  };
}
